services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dev
    ports:
      - 5432:5432

  cache:
    image: redis:7.0.5
    restart: always
    ports:
      - 6379:6379
