site_name: Medical Concept Builder

plugins:
  - search
  - glightbox
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocstrings:
      handlers:
        python:
          selection:
            filters:
              - "^_"  # exlude all members starting with _
          paths: [ ./backend ]

markdown_extensions:
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences

theme:
  name: material
  palette:
    primary: light green
    accent: light blue

nav:
  - Home: index.md
  - Backend: backend.md
