FROM python:3.10

COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv

ARG BUILD_VERSION=bar
ENV MEDCONB_VERSION=$BUILD_VERSION

WORKDIR /usr/src/app

ENV UV_PROJECT_ENVIRONMENT=/opt/venv
COPY pyproject.toml uv.lock ./
RUN uv sync --frozen --no-install-project --no-dev

ENV PATH="/opt/venv/bin:$PATH"

COPY . .

RUN chmod +x start_server.sh

CMD [ "./start_server.sh" ]
